Imports System.Text.RegularExpressions

Public Class MainActivity
    Dim count As Integer

    ' Handling Numbers only for StartInput Text box
    Private Sub number_Handling(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles StartInput.KeyPress
        If Not Char.IsNumber(e.KeyChar) AndAlso Not Char.IsControl(e.KeyChar) Then
            e.Handled = True
        End If
    End Sub
    Private Sub number_TextHandler(ByVal sender As Object, ByVal e As System.EventArgs) Handles StartInput.TextChanged
        Dim digitsOnly As Regex = New Regex("[^\d]")
        StartInput.Text = digitsOnly.Replace(StartInput.Text, "")
    End Sub

    ' Start Seven Segment Counting on the number specified. (Loops to 0 -> 1 after 9)
    Private Sub StartInput_TextChanged(sender As Object, e As EventArgs) Handles StartInput.TextChanged
        If StartInput.Text = "0" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.White
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "1" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.White
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.White
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.Red
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.Red
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "2" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.White
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "3" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "4" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.White
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.White
            segmentE3.BackColor = Color.White
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "5" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.White
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "6" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "7" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.Red
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.White
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.White
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "8" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "9" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.White
            segmentA3.BackColor = Color.White
            segmentA4.BackColor = Color.White
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.White
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.White
            segmentE3.BackColor = Color.White
            segmentE4.BackColor = Color.White
            segmentE5.BackColor = Color.White
        End If
    End Sub

    ' Start Click Handler
    Private Sub btnStart_Click(sender As Object, e As EventArgs) Handles btnStart.Click
        Timer1.Interval = 1000
        Timer1.Start()
        If StartInput.Text IsNot "" Then
            count = CInt(StartInput.Text)
        End If
        StartInput.Enabled = False
    End Sub

    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        count = count + 1
        If count Mod 10 = 0 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.White
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 1 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.White
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.White
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.Red
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.Red
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 2 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.White
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 3 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 4 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.White
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.White
            segmentE3.BackColor = Color.White
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 5 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.White
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 6 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 7 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.Red
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.White
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.White
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 8 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.Red
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf count Mod 10 = 9 Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.Red
            segmentA3.BackColor = Color.Red
            segmentA4.BackColor = Color.Red
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.Red
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.Red
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.Red
            segmentC3.BackColor = Color.Red
            segmentC4.BackColor = Color.Red
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.Red
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.Red
            segmentE3.BackColor = Color.Red
            segmentE4.BackColor = Color.Red
            segmentE5.BackColor = Color.White
        ElseIf StartInput.Text = "" Then
            segmentA1.BackColor = Color.White
            segmentA2.BackColor = Color.White
            segmentA3.BackColor = Color.White
            segmentA4.BackColor = Color.White
            segmentA5.BackColor = Color.White
            segmentB1.BackColor = Color.White
            segmentB2.BackColor = Color.White
            segmentB3.BackColor = Color.White
            segmentB4.BackColor = Color.White
            segmentB5.BackColor = Color.White
            segmentC1.BackColor = Color.White
            segmentC2.BackColor = Color.White
            segmentC3.BackColor = Color.White
            segmentC4.BackColor = Color.White
            segmentC5.BackColor = Color.White
            segmentD1.BackColor = Color.White
            segmentD2.BackColor = Color.White
            segmentD3.BackColor = Color.White
            segmentD4.BackColor = Color.White
            segmentD5.BackColor = Color.White
            segmentE1.BackColor = Color.White
            segmentE2.BackColor = Color.White
            segmentE3.BackColor = Color.White
            segmentE4.BackColor = Color.White
            segmentE5.BackColor = Color.White
        End If
    End Sub

    Private Sub btnStop_Click(sender As Object, e As EventArgs) Handles btnStop.Click
        Timer1.Stop()
        StartInput.Enabled = True
    End Sub

    Private Sub btnReset_Click(sender As Object, e As EventArgs) Handles btnReset.Click
        count = 0
        segmentA1.BackColor = Color.White
        segmentA2.BackColor = Color.White
        segmentA3.BackColor = Color.White
        segmentA4.BackColor = Color.White
        segmentA5.BackColor = Color.White
        segmentB1.BackColor = Color.White
        segmentB2.BackColor = Color.White
        segmentB3.BackColor = Color.White
        segmentB4.BackColor = Color.White
        segmentB5.BackColor = Color.White
        segmentC1.BackColor = Color.White
        segmentC2.BackColor = Color.White
        segmentC3.BackColor = Color.White
        segmentC4.BackColor = Color.White
        segmentC5.BackColor = Color.White
        segmentD1.BackColor = Color.White
        segmentD2.BackColor = Color.White
        segmentD3.BackColor = Color.White
        segmentD4.BackColor = Color.White
        segmentD5.BackColor = Color.White
        segmentE1.BackColor = Color.White
        segmentE2.BackColor = Color.White
        segmentE3.BackColor = Color.White
        segmentE4.BackColor = Color.White
        segmentE5.BackColor = Color.White
    End Sub

    Private Sub segmentA2_Click(sender As Object, e As EventArgs) Handles segmentA2.Click

    End Sub
End Class
